
services:
  casa:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - USER_GID=${USER_GID?Run `export USER_GID=$(id -g)`"}
        - USER_UID=${USER_UID?Run `export USER_UID=$(id -u)`"}
        - USERNAME=${USERNAME?Run `export USERNAME=$(whoami)`"}
        - CASA_VERSION=${CASA_VERSION?err"}
    image: casa
    container_name: casa
    environment:
      - DISPLAY=${DISPLAY?Run `export DISPLAY=:0` (or equivalent)"}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR?err"}  # QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-
    volumes:
    # Base:
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USERNAME}/.Xauthority:/home/${USERNAME}/.Xauthority  # not needed?
    # User:
      - ${PWD}/dotcasa:/home/${USERNAME}/.casa  # default ~/.casa folder from current dir (casa-docker repo)
      - ${PWD}/casa:/home/${USERNAME}/casa  # default ~/casa folder from current dir (casa-docker repo)
      - /home/vicente/Documents/research/astrodata:/home/${USERNAME}/astrodata  # added my own folder for work
    devices:
      - "/dev/fuse:mrw"
      - "/dev/dri:/dev/dri"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - "apparmor:unconfined"
    privileged: true
    network_mode: "host"
